sudo: required
dist: trusty
install: true
before_install:
  # node
  - nvm install 7
  # using google chrome for tests
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script:
  - npm i
  - npm update
script:
  - npm run build
  - npm run lint
  - npm t
  - npm run e2e
after_script:
  - cat npm-debug.log | true
cache:
  directories:
    - node_modules/
