version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:1.11.7
    volumes:
      - "./dist:/usr/share/nginx/html"
    ports:
      - "80:80"
    networks:
      - external-network
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:3.4.0
    environment:
      MONGO_PORT_27017_TCP_PORT: 27017
    ports:
      - "27017:27017"
    networks:
      - backend-network
  #https://github.com/mongo-express/mongo-express-docker
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.32.0
    ports:
      - "8081:8081"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_SITE_BASEURL: /
    networks:
      - backend-network
      - external-network
networks:
  external-network:
    driver: bridge
  backend-network:
    driver: bridge
