export default [
  'core-js',
  'ie-shim',
  'zone.js',
  'zone.js/dist/zone.js',
  'ts-helpers',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',
  '@angular/core',
  '@angular/common',
  '@angular/http',
  '@angular/router',
  'rxjs',
  'rxjs/Rx',
];
